import DatabaseController from './Controllers/DatabaseController';
import { SchemaOptions } from './Options/Definitions';
export declare class Config {
    applicationId: string;
    database: DatabaseController;
    version: string;
    _mount: string;
    publicServerURL: string;
    verifyUserEmails?: boolean;
    emailVerifyTokenValidityDuration?: number;
    passwordPolicy?: any;
    expireInactiveSessions?: boolean;
    sessionLength?: number;
    rateLimits?: any[];
    customPages?: any;
    masterKey?: string | (() => Promise<string>);
    masterKeyTtl?: number;
    masterKeyCache?: {
        masterKey: string;
        expiresAt: Date | null;
    };
    pages?: any;
    static get(applicationId: string, mount?: string): Config;
    static put(serverConfiguration: any): any;
    static validateOptions({ customPages, publicServerURL, revokeSessionOnPasswordReset, expireInactiveSessions, sessionLength, defaultLimit, maxLimit, accountLockout, passwordPolicy, masterKeyIps, masterKey, maintenanceKey, maintenanceKeyIps, readOnlyMasterKey, allowHeaders, idempotencyOptions, fileUpload, pages, security, enforcePrivateUsers, enableInsecureAuthAdapters, schema, requestKeywordDenylist, allowExpiredAuthDataToken, logLevels, rateLimit, databaseOptions, extendSessionOnUse, allowClientClassCreation, }: {
        customPages: any;
        publicServerURL: any;
        revokeSessionOnPasswordReset: any;
        expireInactiveSessions: any;
        sessionLength: any;
        defaultLimit: any;
        maxLimit: any;
        accountLockout: any;
        passwordPolicy: any;
        masterKeyIps: any;
        masterKey: any;
        maintenanceKey: any;
        maintenanceKeyIps: any;
        readOnlyMasterKey: any;
        allowHeaders: any;
        idempotencyOptions: any;
        fileUpload: any;
        pages: any;
        security: any;
        enforcePrivateUsers: any;
        enableInsecureAuthAdapters: any;
        schema: any;
        requestKeywordDenylist: any;
        allowExpiredAuthDataToken: any;
        logLevels: any;
        rateLimit: any;
        databaseOptions: any;
        extendSessionOnUse: any;
        allowClientClassCreation: any;
    }): void;
    static validateCustomPages(customPages: any): void;
    static validateControllers({ verifyUserEmails, userController, appName, publicServerURL, emailVerifyTokenValidityDuration, emailVerifyTokenReuseIfValid, }: {
        verifyUserEmails: any;
        userController: any;
        appName: any;
        publicServerURL: any;
        emailVerifyTokenValidityDuration: any;
        emailVerifyTokenReuseIfValid: any;
    }): void;
    static validateRequestKeywordDenylist(requestKeywordDenylist: any): void;
    static validateEnforcePrivateUsers(enforcePrivateUsers: any): void;
    static validateAllowExpiredAuthDataToken(allowExpiredAuthDataToken: any): void;
    static validateAllowClientClassCreation(allowClientClassCreation: any): void;
    static validateSecurityOptions(security: any): void;
    static validateSchemaOptions(schema: SchemaOptions): void;
    static validatePagesOptions(pages: any): void;
    static validateIdempotencyOptions(idempotencyOptions: any): void;
    static validateAccountLockoutPolicy(accountLockout: any): void;
    static validatePasswordPolicy(passwordPolicy: any): void;
    static setupPasswordValidator(passwordPolicy: any): void;
    static validateEmailConfiguration({ emailAdapter, appName, publicServerURL, emailVerifyTokenValidityDuration, emailVerifyTokenReuseIfValid, }: {
        emailAdapter: any;
        appName: any;
        publicServerURL: any;
        emailVerifyTokenValidityDuration: any;
        emailVerifyTokenReuseIfValid: any;
    }): void;
    static validateFileUploadOptions(fileUpload: any): void;
    static validateIps(field: any, masterKeyIps: any): void;
    static validateEnableInsecureAuthAdapters(enableInsecureAuthAdapters: any): void;
    get mount(): string;
    set mount(newValue: string);
    static validateSessionConfiguration(sessionLength: any, expireInactiveSessions: any): void;
    static validateDefaultLimit(defaultLimit: any): void;
    static validateMaxLimit(maxLimit: any): void;
    static validateAllowHeaders(allowHeaders: any): void;
    static validateLogLevels(logLevels: any): void;
    static validateDatabaseOptions(databaseOptions: any): void;
    static validateRateLimit(rateLimit: any): void;
    generateEmailVerifyTokenExpiresAt(): Date;
    generatePasswordResetTokenExpiresAt(): Date;
    generateSessionExpiresAt(): Date;
    unregisterRateLimiters(): void;
    get invalidLinkURL(): any;
    get invalidVerificationLinkURL(): any;
    get linkSendSuccessURL(): any;
    get linkSendFailURL(): any;
    get verifyEmailSuccessURL(): any;
    get choosePasswordURL(): any;
    get requestResetPasswordURL(): string;
    get passwordResetSuccessURL(): any;
    get parseFrameURL(): any;
    get verifyEmailURL(): string;
    loadMasterKey(): Promise<string>;
    get pagesEndpoint(): any;
}
export default Config;
